services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leads_db
    ports:
      - "3306:3306"
